lib/app_web/router.ex
defmodule AppWeb.Router do
  use AppWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {AppWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug AppWeb.Authenticator
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", AppWeb do
    pipe_through :browser

    get "/*fallback", PageController, :fallback

    get "/", PageController, :index
    get "/users/all", PageController, :users
    post "/users/all", PageController, :search_users
    get "/books/all", PageController, :books
    post "/books/all", PageController, :search_books
    get "/transactions/all", PageController, :transactions
    get "/home", PageController, :home
    get "/terms-of-use", PageController, :term_of_use
    get "/privacy-policy", PageController, :privacy_policy
    get "/menus", PageController, :menus
    get "/about-us", PageController, :about_us
    get "/contact-us", PageController, :contact_us
    get "/login", SessionController, :new
    post "/login", SessionController, :create
    delete "/logout", SessionController, :delete

  end


  ## Announcement Routes
  
  scope "/announcements", AppWeb.Announcement, as: :announcement do
    pipe_through :browser

    resources "/", PageController

  end
 

  ## User Routes
  
  scope "/users", AppWeb.User, as: :user do
    pipe_through :browser

    resources "/", PageController, only: [
      :index, :new, :create
    ]
    
    resources "/accounts", AccountController, only: [:new, :create, :show, :delete]

    get "/transactions/:user_id", AccountController, :user_transactions
    get "/accounts/:id/edit-name", AccountController, :edit_name
    put "/accounts/edit-name", AccountController, :update_name
    get "/accounts/:id/change-password", AccountController, :change_password
    put "/accounts/change-password", AccountController, :update_password
    post "/accounts/approves/:id", AccountController, :approve_disapprove_user
    post "/accounts/reset-password/:id", AccountController, :reset_password
  end


  ## Book Routes

  scope "/books", AppWeb.Book, as: :book do
    pipe_through :browser

    resources "/", PageController
    post "/add/new", PageController, :create_book

  end

  ## Lend Routes

  scope "/lends", AppWeb.Lend, as: :lend do
    pipe_through :browser

    get "/new/:book_id", PageController, :new
    post "/", PageController, :create
    get "/", PageController, :index
    get "/books/:id", PageController, :return_lend
    get "/penalty/reports", PageController, :penalty_report
    get "/books/return-lended-book/:id", PageController, :return_lended_book
    post "/books/approve-requests/:id", PageController, :approve_request
    post "/books/reject-requests/:book_id/:id", PageController, :reject_request
    post "/books/release-books/:book_id/:id", PageController, :release_book
    post "/books/lends/return-conditions/:book_id/:id", PageController, :return_book_condition
    post "/books/return-book", PageController, :return_book
    post "/books/return-overdue-book/:book_id/:id", PageController, :return_overdue_book
    get "/requested-books", PageController, :requested_books
    get "/approved-requested-books", PageController, :approved_requested_books
    get "/released-books", PageController, :released_books
    get "/returned-books", PageController, :returned_books
    get "/overdue-books", PageController, :overdue_books
    get "/out-of-stock-books", PageController, :out_of_stock_books

  end


  ## Admin Routes

  scope "/admins", AppWeb.Admin, as: :admin do
    pipe_through :browser

    get "/login", SessionController, :new
    post "/login", SessionController, :create
    delete "/logout", SessionController, :delete

    get "/list-admins", PageController, :list_admins
    get "/list-reservations", PageController, :list_reservations
    resources "/", PageController, only: [
      :index, :new, :create, :show, :edit, :update, :delete
    ]

     get "/accounts/:id/edit-username", AccountController, :edit_username
     put "/accounts/update-username", AccountController, :update_username
     get "/accoutns/:id/change-password", AccountController, :change_password
     put "/accounts/update-password", AccountController, :update_password

  end


  # Other scopes may use custom stacks.
  # scope "/api", AppWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: AppWeb.Telemetry
    end
  end
end

lib/app_web/templates/page/about-us.html.eex
<nav>
  <div class="logo-name-container">
    <div id="lib-logo">
      <img src="/images/lib-logo.png"/>
    </div>

    <div id="schoolname">ICCT COLLEGES
      <p id="tagname">Library Information Management System</p>
    </div>
  </div>
</nav>

<div class="main">
  <%= render(AppWeb.SharedView, "nav.html", conn: @conn) %>
 
  <div class="sub-container">
    <%= render(AppWeb.SharedView, "back-navigation.html", conn: @conn, title: "About Us") %>

    <div class="page-content">
      <p><strong>ICCT COLLEGES online library information management system</strong> is a highly integrated, user-friendly, and compatible library automated system for complete computerization of all the in-house operations of library. The library management software is intuitive, efficient, and compliant.</p>
      <p>The integrated library software are developed in consultation with the help of senior library professionals and it is currently used by the senior high school library at ICCT COLLEGES.</p>
    </div>
    <%= render(AppWeb.SharedView, "footer.html", conn: @conn) %>
  </div>
</div>

lib/app_web/templates/page/books.html.eex
<nav>
  <div class="logo-name-container">
    <div id="lib-logo">
      <img src="/images/lib-logo.png"/>
    </div>

    <div id="schoolname">ICCT COLLEGES
      <p id="tagname">Library Information Management System</p>
    </div>
  </div>
</nav>

<div class="main">
  <%= render(AppWeb.SharedView, "nav.html", conn: @conn) %>

  <div class="sub-container">
    <div class="page-content"> 
      <%= form_for @conn, Routes.page_path(@conn, :search_books), fn f -> %>
      <label>Category: 
	<%= select f, :category, [options: [
	  "All": "All",
	  "Circulation": "Circulation",
	  "Filipiniana": "Filipiniana",
	  "Fiction": "Fiction"
	    ]] %>
      </label>
      <div style="display:flex;margin-top:-1rem;">
	<%= text_input f, :title, placeholder: "Search book title.." %>
	<%= submit "Search" %>
      </div>
      <% end %>

      <%= cond do %>
      <% @books == nil -> %>
      <p></p>
      <% @books != nil && @books != [] -> %>
      <div class="uploads-container">
	<%= for book <- @books do %>
	    <div class="upload-container">
	      <a href="<%= Routes.book_page_path(@conn, :show, book.id) %>">
		<img src="/images/book.png"/>
		<div class="upload-title-description">
		  <p class="upload-title">
		    <strong><%= book.title %></strong>
		  </p>
		  <div class="upload-description">
		    Available: <%= book.available %>
		  </div>
		</div>
	      </a>
	    </div>
	    <% end %>
      </div>
      <% true -> %>
	<p>No results found!</p>
	<% end %>
	<br><br>
      </div>
    
    <%= render(AppWeb.SharedView, "footer.html", conn: @conn) %>
  </div>
</div>

lib/app_web/templates/page/contact-us.html.eex
<nav>
  <div class="logo-name-container">
    <div id="lib-logo">
      <img src="/images/lib-logo.png"/>
    </div>

    <div id="schoolname">ICCT COLLEGES
      <p id="tagname">Library Information Management System</p>
    </div>
  </div>
</nav>

<div class="main">
  <%= render(AppWeb.SharedView, "nav.html", conn: @conn) %>
  
  <div class="sub-container">
    <%= render(AppWeb.SharedView, "back-navigation.html", conn: @conn, title: "Contact Us") %>
    <div class="page-content">
      <div class="contacts">
	<img src="/images/pcu-tel.png"/>
	<span> 09091234567</span>
      </div>
      <div class="contacts">
	<img src="/images/pcu-email.png"/>
	<span>sample@gmail.com</span>
      </div>
      <div class="contacts">
	<img src="/images/pcu-location.png"/>
	<span>Sample street, Sample City, Philippines</span>
      </div>
    </div>
    <%= render(AppWeb.SharedView, "footer.html", conn: @conn) %>
  </div>
</div>

lib/app_web/templates/page/fallback.html.eex
<p style="margin:50px;text-align:center;">This website is temporarily down or undergoing maintenance. Please check again later or contact the developer!</p>

lib/app_web/templates/page/index.html.eex
<nav>
  <div class="logo-name-container">  
    <div id="lib-logo">
      <img src="/images/lib-logo.png"/>  
    </div>
    
    <div id="schoolname"><%= company_name() %>
      <p id="tagname">Library Information Management System</p>
    </div>
  </div>
  
  <div class="menus">
    <li><a href="<%= Routes.session_path(@conn, :new) %>">SIGN IN</a></li>
    <li><a href="<%= Routes.page_path(@conn, :about_us) %>">ABOUT</a></li>
  </div>
</nav>

<div class="sm-nav-container">
  <img src="/images/lib-logo.png"/>
  <h1><%= company_name() %></h1>
  <p>LIBRARY INFORMATION MANAGEMENT SYSTEM</p>

  <div id="sm-open-close-toggle-container">
    <div id="open">&#8801;</div>
    <div id="close">&times;</div>
  </div>
  <div id="sm-nav-options-container">
    <div><%= link "LOGIN", to: Routes.session_path(@conn, :new) %></div>
    <div><%= link "REGISTER", to: Routes.user_page_path(@conn, :new) %></div>
  
  </div>

</div>

<div class="sub-container">  

  <%= render(AppWeb.SharedView, "flash-messages.html", conn: @conn) %>
  
  <div class="landing-page-content-container">

    <div class="slider-container">
      <div class="slider-wrapper">
	<img src="/images/lib-image1.jpg"/>
	<img src="/images/lib-image2.jpg"/>
	<img src="/images/lib-image3.jpg"/>
      </div>
    </div>

    <div id="home-page-content-container">
      <br>
      <p><strong>[<%= company_name() %>] Online library Information Management System</strong> is a highly integrated, user-friendly, and compatible library automated system for complete computerization of all the in-house operations of library. The library management software is intuitive, efficient, and compliant.</p>
      <p>The integrated library software are developed in consultation with the help of senior library professionals and it is currently used by the senior high school library at [<%= company_name() %>].</p>
    </div>
  </div>
</div>

<footer id="h-footer">
  <div class="footer-logo-container">
    <img src="/images/lib-logo.png"/>
  </div>

  <p class="footer-company-name">Library Information Management System</p>
  <div class="footer-options">
    <li><%= link "Home", to: Routes.page_path(@conn, :index) %></li>
    <li><%= link "About Us", to: Routes.page_path(@conn, :about_us) %></li>
    <li><%= link "Terms Of Use", to: Routes.page_path(@conn, :term_of_use) %></li>
    <li><%= link "Privacy Policy", to: Routes.page_path(@conn, :privacy_policy) %></li>
    <%= if @conn.assigns.current_admin || @conn.assigns.current_user do %>
    <% else %>
    <li><%= link "Sign In", to: Routes.session_path(@conn, :new) %></li>
    <li><%= link "Contact Us", to: Routes.page_path(@conn, :contact_us) %></li>
    <% end %>
  </div>

  <div class="copyright">
    <p>Copyright &copy; 2023 <%= company_name() %>. <p>
      <p>All Rights Reserved.</p>
  </div>
</footer>

lib/app_web/templates/page/menus.html.eex
<%= render(AppWeb.SharedView, "back-navigation.html", conn: @conn, title: "Menus") %>

<div class="sub-container">
  <div class="menu-categories-container">
    <%= if @current_admin do %>

    <a href="<%= Routes.admin_page_path(@conn, :index) %>">
    <div class="menu-category bg-border-red">
      Admin Dashboard
    </div>
    </a>
    <% end %>
    <%= if @current_user do %>
    <a href="<%= Routes.user_account_path(@conn, :show, @current_user.id) %>">
    <div class="menu-category bg-border-yellowgreen">
      My Account
    </div>
    </a>
    <% end %>
    <a href="<%= Routes.page_path(@conn, :index) %>">
    <div class="menu-category bg-border-lightblue">
      Home
    </div>
    </a>
    <a href="<%= Routes.book_page_path(@conn, :index) %>">
    <div class="menu-category bg-border-green">
      Books
    </div>
    </a>
    <a href="">
    <div class="menu-category bg-border-red">
      Privacy Policy
    </div>
    </a>
    <a href="">
    <div class="menu-category bg-border-lightblue">
      Terms Of Use
    </div>
    </a>
    <a href="">
    <div class="menu-category bg-border-yellowgreen">
      About
    </div>
    </a>
    <%= if @conn.assigns.current_admin || @conn.assigns.current_user do %>
    <%= link "Log Out", to: Routes.session_path(@conn, :delete), method: :delete, class: "menu-category bg-border-red", data: [confirm: "Are you sure?"]  %>
    
    <% else %>
    <a href="<%= Routes.session_path(@conn, :new) %>">
    <div class="menu-category bg-border-orange">
      Log in
    </div>
    </a>
    <a href="<%= Routes.user_account_path(@conn, :new) %>">
    <div class="menu-category bg-border-yellowgreen">
      Sign up
    </div>
    </a>
    <% end %>
  </div>
</div>


<%= render(AppWeb.SharedView, "footer.html", conn: @conn) %>

lib/app_web/templates/page/term-of-use.html.eex
<nav>
  <div class="logo-name-container">
    <div id="lib-logo">
      <img src="/images/lib-logo.png"/>
    </div>

    <div id="schoolname">ICCT COLLEGES
      <p id="tagname">Library Information Management System</p>
    </div>
  </div>

  <div class="menus">
    <!--
    <li><a href="<%= Routes.session_path(@conn, :new) %>">SIGN IN</a></li>
    <li><a href="<%= Routes.page_path(@conn, :contact_us) %>">CONTACT US</a></li>
    <li><a href="<%= Routes.page_path(@conn, :about_us) %>">ABOUT</a></li>
    -->
  </div>
</nav>

<div class="main">

  <%= render(AppWeb.SharedView, "nav.html", conn: @conn) %>
  
  <div class="sub-container">
    <%= render(AppWeb.SharedView, "back-navigation.html", conn: @conn, title: "Terms Of Use") %>
    <div class="page-content">

      <h3><strong>Library Rules:</strong></h3>
      <p>As a member of the University you have agreed to the following terms and conditions of use for the Online Library management system Please pay particular attention to clauses 2, 3 and 6 in the General terms of use.</p>
      <blockquote>
	<p>"I acknowledge and agree that resources and their content the "Licensed Material" are protected by copyright as stated in the <em>Copyright Acknowledgement</em> and their use is subject to limitations and Agreements which are summarized in the Terms of Use listed below.</p>
	<p>Details of Agreements for specific resources are available online, and I undertake to read these when I first log in to use each specific resources.</p>
	<p>I shall regard any passwords provided as personal to me and I undertake not to divulge such to a third party."</p>
      </blockquote>

      <h4><strong>I) GENERAL TERMS OF USE</strong></h4>
      <p>Each person must read and abide by Copyright Acknowledgement.</p>
      <div class="page-content">
	<ul>
	  <li>Use of the Licensed Material is restricted to the following purposes: teaching; research; personal educational development; administration and management of the business of the University; and development work associated with any of the aforementioned.</li>
	  <li>Use of the Licensed Material is not permitted for consultancy or services leading to commercial exploitation of the Licensed Material nor for work of significant benefit to the employer of students on industrial placement or part-time courses without prior agreement of the Vendor.</li>
	  <li>Users may print, or download and save, single copies of extracts of the Licensed Material (for example, one chapter, one article or results of searches of the data) for their own personal use.</li>
	  <li>Users must comply with the provisions of law relating to the misuse of computing facilities, and shall not deliberately impair or undermine the usability or performance of computing facilities, the communication network or stored information.</li>
	  <li>Users are required to take all reasonable precautions to maintain integrity of passwords and any other security measures.</li>
	  <li>Users are required to comply with any special conditions of use relating to individual databases which may be given in the user documentation available to registered users.</li>
	  <li>Users are required to respect Intellectual Property rights, including copyright and database right, in the Licensed Material. Failure to do so may result in:</li>
	  <ul>
	    <li>the imposition of restrictions on use of IT Facilities and Systems;</li>
	    <li>withdrawal of access to all Authorised Users;</li>
	    <li>withdrawal of offending material;</li>
	    <li>fines, </li>
	    <li>and recovery of any costs incurred by the University as a result of the breach.</li>
	  </ul>
	</ul>
      </div>

      <h4><strong>II) COPYRIGHT ACKNOWLEDGEMENT</strong></h4>
      <blockquote><em>"I agree</em> that my usage of any Software or Computer readable Datasets, hereafter referred to as the Product, issued or otherwise made available to me by a School or Department of The University of Reading is subject to the following conditions:"</blockquote>
      <ul>
	<li>I will ensure that all the requirements of the agreements or contracts under which the Product is held by The University will be maintained. (Copies of the relevant agreements or contracts may be seen by application to the School or Department which made the Product available).</li>
	<li>I will not remove or alter the Copyright Statement on any copies of Product used by me.</li>
	<li>I will ensure the Security and Confidentiality of any copy released to me, and will not make any further copies from it or knowingly permit others to do so.</li>
	<li>I will use the Product for the purposes defined in the Agreement, and only on computer systems covered by the Agreement.</li>
	<li>I will not incorporate a modified version of the Product in any program written by me without express permission of the Licensor.</li>
	<li>I will not reverse engineer or decompile the Product or attempt to do so without such permission explicitly being permitted within the terms of the Agreement for the use of the Product.</li>
	<li>I will return all copies of the Product at the end of the course/year/period of employment or when requested to do so."</li>
      </ul>

      <p><strong>The University of Reading reserves its right to take legal action against individuals who cause it to be involved in legal proceedings as a result of violation of its licensing agreements.</strong></p>
    </div>

    <%= render(AppWeb.SharedView, "footer.html", conn: @conn) %>
  </div>
</div>

lib/app_web/templates/page/transactions.html.eex
<nav>
  <div class="logo-name-container">
    <div id="lib-logo">
      <img src="/images/lib-logo.png"/>
    </div>

    <div id="schoolname">ICCT COLLEGES
      <p id="tagname">Library Information Management System</p>
    </div>
  </div>
</nav>

<div class="main">
  <%= render(AppWeb.SharedView, "nav.html", conn: @conn) %>

  <div class="sub-container">
    <%= render(AppWeb.SharedView, "back-navigation.html", conn: @conn, title: "Transactions") %>

    <div class="page-content">
      <div class="menu-categories-container">
	<a href="<%= Routes.lend_page_path(@conn, :released_books) %>">
	  <div class="menu-category bg-border-lightblue"><i class="fa fa-book"></i>
          Released Books - <%= length(@released_books) %>
	  </div>
	</a>

	<a href="<%= Routes.lend_page_path(@conn, :requested_books) %>">
	  <div class="menu-category bg-border-lightblue"><i class="fa fa-book"></i>
          Requested Books - <%= length(@requested_books) %>
	  </div>
	</a>

	<a href="<%= Routes.lend_page_path(@conn, :approved_requested_books) %>">
	  <div class="menu-category bg-border-lightblue"><i class="fa fa-book"></i>
         Approved Requests - <%= length(@approved_requested_books) %>
	  </div>
	</a>

	<a href="<%= Routes.lend_page_path(@conn, :returned_books) %>">
	  <div class="menu-category bg-border-lightblue"><i class="fa fa-book"></i>
         Returned Books - <%= length(@returned_books) %>
	  </div>
	</a>

	<a href="<%= Routes.lend_page_path(@conn, :overdue_books) %>">
	  <div class="menu-category bg-border-lightblue"><i class="fa fa-book"></i>
          Overdue Books - <%= length(@overdue_books) %>
	  </div>
	</a>

	<a href="<%= Routes.lend_page_path(@conn, :out_of_stock_books) %>">
	  <div class="menu-category bg-border-lightblue"><i class="fa fa-book"></i>
          Out of Stock Books - <%= length(@out_of_stock_books) %>
	  </div>
	</a>

	<a href="<%= Routes.lend_page_path(@conn, :penalty_report) %>">
	  <div class="menu-category bg-border-lightblue">
          Generate Report
	  </div>
	</a>
      </div>
    </div>
    <%= render(AppWeb.SharedView, "footer.html", conn: @conn) %>
  </div>
</div>

lib/app_web/templates/page/users.html.eex
<nav>
  <div class="logo-name-container">
    <div id="lib-logo">
      <img src="/images/lib-logo.png"/>
    </div>

    <div id="schoolname">ICCT COLLEGES
      <p id="tagname">Library Information Management System</p>
    </div>
  </div>
</nav>

<div class="main">
  <%= render(AppWeb.SharedView, "nav.html", conn: @conn) %>

  <div class="sub-container">
    <div class="page-content">
      <%= form_for @conn, Routes.page_path(@conn, :search_users), fn f -> %>

      <label>CATEGORY:
	<%= select f, :category, [options: ["Admin": "Admin", "Student": "Student"]] %>
      </label>

      <div style="display:flex;">
	<%= text_input f, :query, placeholder: "Search username or lastname.." %>
	<%= submit "Search" %>
      </div>
      <% end %>

      <%= cond do %>
      <% @admins == nil && @students == nil -> %>
      <p></p>
      <% @admins != nil && @admins != [] -> %>
      <table>
	<thead>
	  <tr>
	    <th>Name</th>
	    <th>Email</th>
	  </tr>
	</thead>
	<tbody>
	  <%= for admin <- @admins do %>
	      <tr>
		<%= if @current_admin.id == admin.id do %>
		<td><%= link admin.username, to: Routes.admin_page_path(@conn, :show, admin.id) %></td>
		<% else %>
		<td><%= admin.username %></td>
		<% end %>
		<td><%= admin.email %></td>
	      </tr>
	      <% end %>
	</tbody>
      </table>
      <% @students != nil && @students != [] -> %>
	  <div class="sm-user-details">
	    <%= for user <- @students do %>
		<dl>
		  <dt>Name</dt>
		  <dd><%= link username(user.first_name, user.last_name), to: Routes.user_account_path(@conn, :show, user.id) %></dd>
                  <dt>Email</dt>
		  <dd><%= user.email %></dd>
		  <dt>Course</dt>
		  <dd><%= user.course %></dd>
		  <dt>Approve</dt>

		  <%= if user.approve do %>
		  <dd><%= link "True", to: Routes.user_account_path(@conn, :approve_disapprove_user, user.id), method: :post %></dd>
                    <% else %>
                    <dd><%= link "False", to: Routes.user_account_path(@conn, :approve_disapprove_user, user.id), method: :post %></dd>
                    <% end %>
		    <dt>Action</dt>
                    <dd><%= link "Delete", to: Routes.user_account_path(@conn, :delete, user.id), method: :delete, class: "color-red", data: [confirm: "Are you sure to delete this account?"] %></dd>
                </dl>
		<hr/>
		<% end %>
	  </div>
	  
	  <div class="l-user-details">
	  <table>
	    <thead>
	      <tr>
		<th>Name</th>
		<th>ID</th>
		<th>Email</th>
		<th>Course</th>
		<th>Approved?</th>
		<th></th>
	      </tr>
	    </thead>
	    <tbody>
	      <%= for user <- @students do %>
		  <tr>
		    <td><%= link username(user.first_name, user.last_name), to: Routes.user_account_path(@conn, :show, user.id) %></td>
		    <td><%= user.student_id %></td>		    <td><%= user.email %></td>
		    <td><%= user.course %></td>
		    <%= if user.approve do %>
		    <td><%= link "True", to: Routes.user_account_path(@conn, :approve_disapprove_user, user.id), method: :post %></td>
		    <% else %>
		    <td><%= link "False", to: Routes.user_account_path(@conn, :approve_disapprove_user, user.id), method: :post %></td>
		    <% end %>
		    <td><%= link "Delete", to: Routes.user_account_path(@conn, :delete, user.id), method: :delete, class: "color-red", data: [confirm: "Are you sure to delete this account?"] %></td>
		  </tr>
		  <% end %>
	    </tbody>
	  </table>
	  </div>
	  <% true -> %>
	      <p>No results found!</p>
	      <% end %>
    </div>
    <br><br>
    <%= render(AppWeb.SharedView, "footer.html", conn: @conn) %>
  </div>
</div>